import fs from "node:fs/promises";
import path from "node:path";
import { Client } from "pg";
import {
  parseDatabaseIdentity,
  resolveTestDatabaseUrl,
  runPackageBin,
  serverRoot,
} from "./test-db.lib.js";

// Provisions a throwaway database holding *only* Lab 2-era schema and data
// — the two migrations that predate Lab 3's User/Session/Ticket evolution
// — so server/tests/lab-03/migration.test.ts can apply the Lab 3 migration
// to it and assert the rename/backfill preserves every row
// (docs/lab-03/specification.md §7.4, tests.md §1.4 and §2.6 MIG-01..MIG-06).
//
// This is a *separate* database from the shared `toktickit_test` database
// the rest of the suite uses (tests/setup/global-setup.ts): that database
// is already fully migrated to the Lab 3 schema before any test file runs,
// so it can never stand in for "a database holding Lab 2 data". This
// fixture database instead starts from nothing on every call — dropped,
// recreated, migrated only as far as Lab 2 went, then hand-seeded with
// representative Lab 2-era rows via raw SQL, since the current (Lab
// 3-shaped) Prisma Client has no model for the pre-rename `RequesterUser`
// table and cannot write rows the way `prisma/seed.ts` does.

const LAB2_MIGRATIONS = [
  "20260806101642_init_category",
  "20260906035347_add_lab2_ticketing",
] as const;

const FIXTURE_SUFFIX = "_lab2fixture";

/** Derives the fixture database's URL from the test database's URL by
 * appending a fixed suffix to the database name — same host, port and
 * credentials, a sibling database name. Always contains "test" (inherited
 * from the test database name), satisfying the same safety property
 * `resolveTestDatabaseUrl` already enforced on its input. */
function deriveFixtureUrl(testDatabaseUrl: string): string {
  const identity = parseDatabaseIdentity(testDatabaseUrl);
  const fixtureUrl = new URL(testDatabaseUrl);
  fixtureUrl.pathname = `/${identity.database}${FIXTURE_SUFFIX}`;
  return fixtureUrl.toString();
}

/** Drops (if present) and recreates the fixture database, so every call
 * starts from a genuinely empty database — the "restore the snapshot"
 * tests.md §1.4 describes. `WITH (FORCE)` (Postgres 13+) disconnects any
 * lingering session from a prior run first, so this never fails with
 * "database is being accessed by other users". */
async function recreateDatabase(fixtureUrl: string): Promise<void> {
  const dbName = parseDatabaseIdentity(fixtureUrl).database;

  const adminUrl = new URL(fixtureUrl);
  adminUrl.pathname = "/postgres";

  const admin = new Client({ connectionString: adminUrl.toString() });
  await admin.connect();
  try {
    await admin.query(`DROP DATABASE IF EXISTS "${dbName}" WITH (FORCE)`);
    await admin.query(`CREATE DATABASE "${dbName}"`);
  } finally {
    await admin.end();
  }
}

/**
 * Applies only the two Lab 2-era migrations to `fixtureUrl`, via a
 * throwaway Prisma config whose `migrations.path` points at a temp
 * directory holding copies of just those two migration folders.
 * `prisma migrate deploy` always applies every pending migration in its
 * configured folder, in order — restricting *which migrations exist* is
 * the only way to make it stop short of the Lab 3 migration.
 *
 * The temp config and migrations directory live under `server/`, not the
 * OS temp directory: Node module resolution for the config file's own
 * `import { defineConfig } from "prisma/config"` walks up from the config
 * file's location looking for `node_modules`, which only succeeds while
 * the file stays somewhere under `server/`.
 */
async function applyLab2Migrations(fixtureUrl: string): Promise<void> {
  const tmpRoot = path.join(serverRoot, "scripts", ".lab2-fixture-tmp");
  await fs.rm(tmpRoot, { recursive: true, force: true });
  const tmpMigrations = path.join(tmpRoot, "migrations");
  await fs.mkdir(tmpMigrations, { recursive: true });

  await fs.copyFile(
    path.join(serverRoot, "prisma/migrations/migration_lock.toml"),
    path.join(tmpMigrations, "migration_lock.toml")
  );
  for (const name of LAB2_MIGRATIONS) {
    const dest = path.join(tmpMigrations, name);
    await fs.mkdir(dest, { recursive: true });
    await fs.copyFile(
      path.join(serverRoot, "prisma/migrations", name, "migration.sql"),
      path.join(dest, "migration.sql")
    );
  }

  const configPath = path.join(tmpRoot, "prisma.config.ts");
  await fs.writeFile(
    configPath,
    [
      'import { defineConfig } from "prisma/config";',
      "",
      "// Generated by scripts/test-db-lab2-fixture.lib.ts — safe to delete.",
      "export default defineConfig({",
      `  schema: ${JSON.stringify(path.join(serverRoot, "prisma/schema.prisma"))},`,
      `  migrations: { path: ${JSON.stringify(tmpMigrations)} },`,
      '  datasource: { url: process.env["DATABASE_URL"] },',
      "});",
      "",
    ].join("\n"),
    "utf-8"
  );

  try {
    runPackageBin("prisma", ["migrate", "deploy", "--config", configPath], {
      cwd: serverRoot,
      env: { ...process.env, DATABASE_URL: fixtureUrl },
      stdio: "pipe",
    });
  } finally {
    await fs.rm(tmpRoot, { recursive: true, force: true });
  }
}

/**
 * Hand-seeds representative Lab 2-era rows via raw SQL, matching the
 * pre-Lab-3 table shapes exactly (no `role`, `passwordHash`, `itPriority`,
 * `ownerId`, ... columns exist yet at this point). Includes one
 * mixed-case-email Requester so MIG-04 (email lower-casing) has something
 * real to assert against, and one Attachment with `removedById` set so the
 * rename's FK preservation (MIG-01) is exercised on both foreign keys that
 * point at the renamed table (`Ticket.requesterId` and
 * `Attachment.removedById`), not only the first one.
 */
async function seedLab2EraData(fixtureUrl: string): Promise<void> {
  const client = new Client({ connectionString: fixtureUrl });
  await client.connect();
  try {
    const category = await client.query<{ id: number }>(
      `INSERT INTO "Category" (name, "isActive") VALUES ('Hardware', true) RETURNING id`
    );
    const relatedSystem = await client.query<{ id: number }>(
      `INSERT INTO "RelatedSystem" (name, "isActive") VALUES ('Printer', true) RETURNING id`
    );
    const categoryId = category.rows[0]!.id;
    const relatedSystemId = relatedSystem.rows[0]!.id;

    const requesterRows = await client.query<{ id: number }>(
      `INSERT INTO "RequesterUser" (name, email, "isActive", "updatedAt")
       VALUES
         ('Lab2 Alice', 'lab2.alice@example.edu', true, now()),
         ('Lab2 Bob', 'lab2.bob@example.edu', true, now()),
         ('Lab2 Mixed Case', 'Mixed.Case@Example.EDU', true, now()),
         ('Lab2 Inactive', 'lab2.inactive@example.edu', false, now())
       RETURNING id`
    );
    const [aliceId, bobId, mixedCaseId] = requesterRows.rows.map((r) => r.id);

    const ticketRows = await client.query<{ id: number }>(
      `INSERT INTO "Ticket"
         ("ticketNumber", "requesterId", "categoryId", "relatedSystemId",
          summary, description, "requestedPriority", status, "updatedAt")
       VALUES
         ('TKT-LAB2-000001', $1, $4, $5, 'Lab 2 fixture ticket 1', 'Fixture description, at least twenty characters.', 'MEDIUM', 'NEW', now()),
         ('TKT-LAB2-000002', $2, $4, $5, 'Lab 2 fixture ticket 2', 'Fixture description, at least twenty characters.', 'HIGH', 'NEW', now()),
         ('TKT-LAB2-000003', $3, $4, $5, 'Lab 2 fixture ticket 3 (mixed-case-email owner)', 'Fixture description, at least twenty characters.', 'LOW', 'NEW', now())
       RETURNING id`,
      [aliceId, bobId, mixedCaseId, categoryId, relatedSystemId]
    );
    const [ticket1Id, ticket2Id] = ticketRows.rows.map((r) => r.id);

    await client.query(
      `INSERT INTO "Attachment"
         ("ticketId", "originalFilename", "storedFilename", "mimeType", "fileSize",
          "isRemoved", "removedAt", "removedReason", "removedById")
       VALUES
         ($1, 'notes.txt', 'lab2-fixture-notes.txt', 'text/plain', 128, false, NULL, NULL, NULL),
         ($2, 'old-log.txt', 'lab2-fixture-old-log.txt', 'text/plain', 256, true, now(), 'Superseded by a newer file.', $3)`,
      [ticket1Id, ticket2Id, aliceId]
    );
  } finally {
    await client.end();
  }
}

/**
 * Ensures the Lab 2-era fixture database exists, holds only the Lab 2
 * schema, and is seeded with representative Lab 2-era data. Always starts
 * by dropping and recreating it, so the result is identical on every call
 * regardless of what a previous run (or a previously-applied Lab 3
 * migration) left behind. Returns the fixture database's URL.
 */
export async function resetLab2FixtureDatabase(): Promise<string> {
  const testDatabaseUrl = resolveTestDatabaseUrl();
  const fixtureUrl = deriveFixtureUrl(testDatabaseUrl);

  await recreateDatabase(fixtureUrl);
  await applyLab2Migrations(fixtureUrl);
  await seedLab2EraData(fixtureUrl);

  return fixtureUrl;
}
